// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat.proto
// Protobuf Java Version: 4.32.0

@com.google.protobuf.Generated
public final class ChatOuterClass {
  private ChatOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ChatOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Chat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sendingPlayerID = 1;</code>
     * @return The sendingPlayerID.
     */
    int getSendingPlayerID();

    /**
     * <code>int32 receivingPlayerID = 2;</code>
     * @return The receivingPlayerID.
     */
    int getReceivingPlayerID();

    /**
     * <code>string chatContent = 3;</code>
     * @return The chatContent.
     */
    java.lang.String getChatContent();
    /**
     * <code>string chatContent = 3;</code>
     * @return The bytes for chatContent.
     */
    com.google.protobuf.ByteString
        getChatContentBytes();

    /**
     * <code>bool spoiler = 4;</code>
     * @return The spoiler.
     */
    boolean getSpoiler();
  }
  /**
   * Protobuf type {@code Chat}
   */
  public static final class Chat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Chat)
      ChatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        Chat.class.getName());
    }
    // Use Chat.newBuilder() to construct.
    private Chat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Chat() {
      chatContent_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatOuterClass.internal_static_Chat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatOuterClass.internal_static_Chat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatOuterClass.Chat.class, ChatOuterClass.Chat.Builder.class);
    }

    public static final int SENDINGPLAYERID_FIELD_NUMBER = 1;
    private int sendingPlayerID_ = 0;
    /**
     * <code>int32 sendingPlayerID = 1;</code>
     * @return The sendingPlayerID.
     */
    @java.lang.Override
    public int getSendingPlayerID() {
      return sendingPlayerID_;
    }

    public static final int RECEIVINGPLAYERID_FIELD_NUMBER = 2;
    private int receivingPlayerID_ = 0;
    /**
     * <code>int32 receivingPlayerID = 2;</code>
     * @return The receivingPlayerID.
     */
    @java.lang.Override
    public int getReceivingPlayerID() {
      return receivingPlayerID_;
    }

    public static final int CHATCONTENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object chatContent_ = "";
    /**
     * <code>string chatContent = 3;</code>
     * @return The chatContent.
     */
    @java.lang.Override
    public java.lang.String getChatContent() {
      java.lang.Object ref = chatContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatContent_ = s;
        return s;
      }
    }
    /**
     * <code>string chatContent = 3;</code>
     * @return The bytes for chatContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatContentBytes() {
      java.lang.Object ref = chatContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPOILER_FIELD_NUMBER = 4;
    private boolean spoiler_ = false;
    /**
     * <code>bool spoiler = 4;</code>
     * @return The spoiler.
     */
    @java.lang.Override
    public boolean getSpoiler() {
      return spoiler_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sendingPlayerID_ != 0) {
        output.writeInt32(1, sendingPlayerID_);
      }
      if (receivingPlayerID_ != 0) {
        output.writeInt32(2, receivingPlayerID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chatContent_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, chatContent_);
      }
      if (spoiler_ != false) {
        output.writeBool(4, spoiler_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sendingPlayerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendingPlayerID_);
      }
      if (receivingPlayerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, receivingPlayerID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chatContent_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, chatContent_);
      }
      if (spoiler_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, spoiler_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatOuterClass.Chat)) {
        return super.equals(obj);
      }
      ChatOuterClass.Chat other = (ChatOuterClass.Chat) obj;

      if (getSendingPlayerID()
          != other.getSendingPlayerID()) return false;
      if (getReceivingPlayerID()
          != other.getReceivingPlayerID()) return false;
      if (!getChatContent()
          .equals(other.getChatContent())) return false;
      if (getSpoiler()
          != other.getSpoiler()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDINGPLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getSendingPlayerID();
      hash = (37 * hash) + RECEIVINGPLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getReceivingPlayerID();
      hash = (37 * hash) + CHATCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getChatContent().hashCode();
      hash = (37 * hash) + SPOILER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSpoiler());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatOuterClass.Chat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatOuterClass.Chat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatOuterClass.Chat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatOuterClass.Chat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatOuterClass.Chat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatOuterClass.Chat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatOuterClass.Chat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatOuterClass.Chat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ChatOuterClass.Chat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ChatOuterClass.Chat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatOuterClass.Chat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatOuterClass.Chat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Chat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Chat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Chat)
        ChatOuterClass.ChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatOuterClass.internal_static_Chat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatOuterClass.internal_static_Chat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatOuterClass.Chat.class, ChatOuterClass.Chat.Builder.class);
      }

      // Construct using ChatOuterClass.Chat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sendingPlayerID_ = 0;
        receivingPlayerID_ = 0;
        chatContent_ = "";
        spoiler_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatOuterClass.internal_static_Chat_descriptor;
      }

      @java.lang.Override
      public ChatOuterClass.Chat getDefaultInstanceForType() {
        return ChatOuterClass.Chat.getDefaultInstance();
      }

      @java.lang.Override
      public ChatOuterClass.Chat build() {
        ChatOuterClass.Chat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ChatOuterClass.Chat buildPartial() {
        ChatOuterClass.Chat result = new ChatOuterClass.Chat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ChatOuterClass.Chat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sendingPlayerID_ = sendingPlayerID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.receivingPlayerID_ = receivingPlayerID_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.chatContent_ = chatContent_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.spoiler_ = spoiler_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatOuterClass.Chat) {
          return mergeFrom((ChatOuterClass.Chat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatOuterClass.Chat other) {
        if (other == ChatOuterClass.Chat.getDefaultInstance()) return this;
        if (other.getSendingPlayerID() != 0) {
          setSendingPlayerID(other.getSendingPlayerID());
        }
        if (other.getReceivingPlayerID() != 0) {
          setReceivingPlayerID(other.getReceivingPlayerID());
        }
        if (!other.getChatContent().isEmpty()) {
          chatContent_ = other.chatContent_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getSpoiler() != false) {
          setSpoiler(other.getSpoiler());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sendingPlayerID_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                receivingPlayerID_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                chatContent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                spoiler_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sendingPlayerID_ ;
      /**
       * <code>int32 sendingPlayerID = 1;</code>
       * @return The sendingPlayerID.
       */
      @java.lang.Override
      public int getSendingPlayerID() {
        return sendingPlayerID_;
      }
      /**
       * <code>int32 sendingPlayerID = 1;</code>
       * @param value The sendingPlayerID to set.
       * @return This builder for chaining.
       */
      public Builder setSendingPlayerID(int value) {

        sendingPlayerID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sendingPlayerID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendingPlayerID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendingPlayerID_ = 0;
        onChanged();
        return this;
      }

      private int receivingPlayerID_ ;
      /**
       * <code>int32 receivingPlayerID = 2;</code>
       * @return The receivingPlayerID.
       */
      @java.lang.Override
      public int getReceivingPlayerID() {
        return receivingPlayerID_;
      }
      /**
       * <code>int32 receivingPlayerID = 2;</code>
       * @param value The receivingPlayerID to set.
       * @return This builder for chaining.
       */
      public Builder setReceivingPlayerID(int value) {

        receivingPlayerID_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 receivingPlayerID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceivingPlayerID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receivingPlayerID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object chatContent_ = "";
      /**
       * <code>string chatContent = 3;</code>
       * @return The chatContent.
       */
      public java.lang.String getChatContent() {
        java.lang.Object ref = chatContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chatContent = 3;</code>
       * @return The bytes for chatContent.
       */
      public com.google.protobuf.ByteString
          getChatContentBytes() {
        java.lang.Object ref = chatContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chatContent = 3;</code>
       * @param value The chatContent to set.
       * @return This builder for chaining.
       */
      public Builder setChatContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        chatContent_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string chatContent = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatContent() {
        chatContent_ = getDefaultInstance().getChatContent();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string chatContent = 3;</code>
       * @param value The bytes for chatContent to set.
       * @return This builder for chaining.
       */
      public Builder setChatContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        chatContent_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private boolean spoiler_ ;
      /**
       * <code>bool spoiler = 4;</code>
       * @return The spoiler.
       */
      @java.lang.Override
      public boolean getSpoiler() {
        return spoiler_;
      }
      /**
       * <code>bool spoiler = 4;</code>
       * @param value The spoiler to set.
       * @return This builder for chaining.
       */
      public Builder setSpoiler(boolean value) {

        spoiler_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool spoiler = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpoiler() {
        bitField0_ = (bitField0_ & ~0x00000008);
        spoiler_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Chat)
    }

    // @@protoc_insertion_point(class_scope:Chat)
    private static final ChatOuterClass.Chat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatOuterClass.Chat();
    }

    public static ChatOuterClass.Chat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Chat>
        PARSER = new com.google.protobuf.AbstractParser<Chat>() {
      @java.lang.Override
      public Chat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Chat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Chat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ChatOuterClass.Chat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Chat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\"`\n\004Chat\022\027\n\017sendingPlayerID\030" +
      "\001 \001(\005\022\031\n\021receivingPlayerID\030\002 \001(\005\022\023\n\013chat" +
      "Content\030\003 \001(\t\022\017\n\007spoiler\030\004 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Chat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Chat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Chat_descriptor,
        new java.lang.String[] { "SendingPlayerID", "ReceivingPlayerID", "ChatContent", "Spoiler", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
